### ISSUE TITLE
Get shodan api from home url

### ISSUE THREAD

**Issue by dmknght** [ElevenPaths/HomePWN#1]
**Is your feature request related to a problem? Please describe.**
By default, shodan will save the api key at `$HOME/.shodan/api_key`. By now, homePWN doesn't use that path to save API key.

**Describe the solution you'd like**
Change path to get shodan API key to `$HOME/.shodan/api_key` so users don't have to set key value multiple times (Just need to set api key to use shodan cli only for example).

**Describe alternatives you've considered**

**Additional context**

**Comment by Josue87** [comment]
Hello dmknght,

We think it's a good change, and we've added that feature in this commit: [24248c9](https://github.com/ElevenPaths/HomePWN/commit/24248c994adffdc89a00ae4622a7ed39ae0fb37d).

Thank you.

**Comment by dmknght** [comment]
Tested and worked for me. Thanks for fast change. Issue can be closed now
