### ISSUE TITLE
Failed to execute management command 'le on' (code: 10, error: Busy)

### ISSUE THREAD

**Issue by rbl3210** [ElevenPaths/HomePWN#10]
homePwn >>load discovery/ble
Loading module...
[+] Module loaded!
homePwn (discovery/ble) >> show
Module Info
===========
 Name
 ----
 |_Discovery BLE devices 

 Description
 -----------
 |_With this module you can discover nearby devices with BLE (Bluetooth Low Energy) active. The result will be sorted by RSSI.

 privileges
 ----------
 |_root

 OS
 --
 |_Linux

 Author
 ------
 |_@josueencinar

 Options (Field = Value)
 -----------------------
 |
 |_timeout = 5  (Timeout to wait for search responses. (In seconds))
 |_rssi = -62 (dB signal to filter (min value, example -60))
 |_iface = hci1 (Ble iface index (default to 0 for hci0))

i run kali on the Windows virtual machine,hci1 is usb dongle

please help...

**Comment by rbl3210** [comment]
And i can run hcitool lescan on kali
C:\root\Desktop> hcitool -i hci1 lescan
LE Scan ...
47:CF:59:25:4D:46 (unknown)
66:0B:EB:12:3A:7A (unknown)
2C:2A:D0:F9:EC:6B (unknown)
5F:C1:CC:5C:35:81 (unknown)
5F:C1:CC:5C:35:81 (unknown)
4B:F5:D8:4F:42:76 (unknown)
18:40:B3:F6:FD:B3 (unknown)
78:A7:EB:23:B8:4A (unknown)
78:A7:EB:23:B8:4A (unknown)
12:96:94:0F:F3:0B (unknown)
25:4B:19:A0:90:EB (unknown)
33:B0:ED:5C:06:53 (unknown)
16:07:C5:FF:1D:CC (unknown)
24:83:43:91:80:BD (unknown)
12:96:94:0F:F3:0B (unknown)
7B:E5:9B:E7:56:83 (unknown)
7B:E5:9B:E7:56:83 (unknown)

**Comment by Josue87** [comment]
Sorry, I've seen your settings now. You should set iface with a number (check option description).

If you want to configure hci1 then launch:

- **set iface 1**

No launch set iface hci1.
