### ISSUE TITLE
Unsupported Manufacturer

### ISSUE THREAD

**Issue by westz36** [ElevenPaths/HomePWN#11]
**Describe the bug**

> homePwn (bluetooth/mac-spoof) >> run
Searching bluetooth devices to check MAC...
A nearby device has been found
Trying to change name and MAC
Manufacturer:   Atheros Communications, Inc. (69)
Device address: 00:71:CC:6F:97:7A

Unsupported manufacturer
[!] Execution fault...
`

**Expected behavior**
Mac-Spoof module does not execute, due to manufacture constraint

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 - latest update

**Additional context**

**Comment by Josue87** [comment]
There are Bluetooth devices that do not allow you to change MAC. For example, the Bluetooth that comes by default in my DELL cannot be changed, however, I can make the change of address in a **Bluetooth USB Dongle**.  The devices can be found at Amazon or Aliexpress without any problem.

Regards.
