### ISSUE TITLE
failed install on mac 10.14

### ISSUE THREAD

**Issue by Misschihiro** [ElevenPaths/HomePWN#12]
failed install on macos 10.14

I want to install homepwn on my mac and my macos version is 10.14, when i do: sudo ./install.sh

it will have the following error, so what should i do, how can i install this on macos successfully? please help me, thanks.
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory
    /Users/www/HomePWN-master/owl/googletest
  does not contain a CMakeLists.txt file.
and when i run sudo python3 homePwn.py, it will show the following:
![image](https://user-images.githubusercontent.com/17743767/81143956-a8a54280-8fa5-11ea-97d5-8dff059c9fef.png)
homePwn >>help                                                                                                 

    Core commands
    =============

        Command                    Description
        -------                    -----------
        help                       Help menu
        load <module>              Load module
        modules  [category]        List all modules or a certain category
        find <info>                Search modules with concret info
        exit|quit                  Exit application
        banner                     Show banner
        export                     Save global options  
        import                     Load global options (previously exported)
        tasks <show/kill> [id]     Show tasks running or kill a task
        theme dark|light|default   Change the theme of the tool
        # <command>                Grant terminal commands        
    
    Module commands
    ===============

        Command                    Description
        -------                    -----------
        set <option> <value>       Set value for module's option
        unset <option>             Unset value for module's option
        run                        Run module
        back                       Unload module                                        
        show [options|info]        Show either options or info 
        global <option> <value>    Set global option
    
homePwn >>back                                                                                                 
[!] Error parsing input

**Desktop (please complete the following information):**
 - MCOS: 10.14

**Comment by lucferbux** [comment]
Hi, currently mac is not supported, this error is caused by the parsing library in Python that does not support this platform.
Best recommendation is create a Virtual Machine in a debian-based distro (debian, kali, ubuntu...)

**Comment by Misschihiro** [comment]
> Hi, currently mac is not supported, this error is caused by the parsing library in Python that does not support this platform.
> Best recommendation is create a Virtual Machine in a debian-based distro (debian, kali, ubuntu...)

ok, but I saw, someone installed succeeded on macos in the commits. I meet another error, when I run: load discovery/bluetooth on my ubuntu 18.4, it shows "no module named 'bluetooth', how to deal with this.

**Comment by Josue87** [comment]
Try to install pybluez: 

`pip install pybluez`

Check the requirements in [modules folder](https://github.com/ElevenPaths/HomePWN/blob/master/modules/_requirements.txt).

**Comment by Misschihiro** [comment]
> Try to install pybluez:
> 
> `pip install pybluez`
> 
> Check the requirements in [modules folder](https://github.com/ElevenPaths/HomePWN/blob/master/modules/_requirements.txt).

ok,thanks. Now, I can run it successfully. Thanks.
