### ISSUE TITLE
i cant able to install homepwn on ubuntu18.04 and i use python 3.7 as per readme

### ISSUE THREAD

**Issue by pilotshooter** [ElevenPaths/HomePWN#3]
![homwpwn](https://user-images.githubusercontent.com/56905782/67842139-99899780-fb1f-11e9-9a3c-5333b998c2fe.png)

**Comment by lucferbux** [comment]
Hi, you are not in the application folder, I will add this extra step to avoid confusion, but you just need to locate the script.

**Comment by pilotshooter** [comment]
yup just now found anyhow thanks for the resposne

**Comment by pilotshooter** [comment]
i cant able to get virtual env it throws 
![HomePWN](https://user-images.githubusercontent.com/56905782/67845650-d9537d80-fb25-11e9-91db-ee3b901ce505.png)
an error

**Comment by pilotshooter** [comment]
i just launched the application without a vm and can you provide any readme for all homepwn fn's

**Comment by pilotshooter** [comment]
sucessfully launched homepwn and is there need of any kinda of hardware for scanning..
![homepwn](https://user-images.githubusercontent.com/56905782/67850461-71edfb80-fb2e-11e9-811e-4149d0dfb959.png)
