### ISSUE TITLE
Build for OSX

### ISSUE THREAD

**Issue by iosdec** [ElevenPaths/HomePWN#4]
**Is your feature request related to a problem? Please describe.**
This fails to install on OSX - would be great if it could be ported

**Describe the solution you'd like**
If possible, installation instructions for OSX

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by lucferbux** [comment]
Hi, as we stated in the README, it's mandatory the use of a debian based distro (ubuntu, debian, kali...) as some of the libraries are only compatible with those OS. We recommend to use a Virtual Machine with a Mac.

**Comment by iosdec** [comment]
@lucferbux makes sense - I noticed the bluetooth libraries are completely incompatible.. tried on a dualboot macbook with kali though, works perfect 🙂

**Comment by changtraisitinh** [comment]
i run on macOS success, no error
