### ISSUE TITLE
Change requirements for properly install  prompt_toolkit

### ISSUE THREAD

**Issue by campeador** [ElevenPaths/HomePWN#5]
Hi,

You should add in the requirements.txt and install.sh the version of prompt_toolkit because if don't you get an error when you try to execute sudo python3 homepwn.py

In requirements.txt file, modify:
prompt_toolkit for prompt_toolkit==2.0.10

and the same in the install.sh

Thank you for your job!

**Comment by lucferbux** [comment]
Done!
Thanks for the fix!
