### ISSUE TITLE
Failed to execute management command 'le on' (code: 12, error: Not Supported)

### ISSUE THREAD

**Issue by sergiokelevra** [ElevenPaths/HomePWN#6]
homePwn >>load discovery/ble                                                                        
Loading module...
[+] Module loaded!
homePwn (discovery/ble) >> show                                                                     
Module Info
===========
 Name
 ----
 |_Discovery BLE devices 

 Description
 -----------
 |_With this module you can discover nearby devices with BLE (Bluetooth Low Energy) active. The result will be sorted by RSSI.

 privileges
 ----------
 |_root

 OS
 --
 |_Linux

 Author
 ------
 |_@josueencinar

 Options (Field = Value)
 -----------------------
 |
 |_timeout = 5  (Timeout to wait for search responses. (In seconds))
 |_[OPTIONAL] rssi = None (dB signal to filter (min value, example -60))

homePwn (discovery/ble) >> set rssi -65                                                             
rssi >> -65
homePwn (discovery/ble) >> run                                                                      
Searching BLE devices...

Failed to execute management command 'le on' (code: 12, error: Not Supported)
homePwn (discovery/ble) >>         

I've tried everything, reinstalling, even use, The Crazyradio 2.4GHz radio USB dongle which based on the Nordic Semiconductor nRF24LU1+ SoC. 

Help???

**Comment by DirtyDeep** [comment]
I have the same issue

**Comment by lucferbux** [comment]
Hello, i think i know what's the problem, the module is looking for hci0 interface for default, i might add support for more interface, to check the problem pelase run the command:
`hcitool dev`

And tell me if your dongle is in fact in hci0 or another interface.

**Comment by DirtyDeep** [comment]
Hello,i had run the command of 'hcitool dev',the list of Devices is hci0 myBlueMacAddress ,then I try to discovery/ble model run the command,but have the same issue

**Comment by lucferbux** [comment]
ok, so that wasn't the problem, but again, i will include the option to select the interface.
Are you using the tool in a virtual machine sharing the bluetooth of the host, is it the main machine or are you using usb dongle?

**Comment by DirtyDeep** [comment]
yeah,I used this tool in my main virtual machine ,and I can run the command successful in discovery/bluetooth model

**Comment by lucferbux** [comment]
> yeah,I used this tool in my main virtual machine ,and I can run the command successful in discovery/bluetooth model

ok, and you are using a dongle usb or are you sharing the bluetooth of your host machine?
I'm asking you that because I have problems too using the bluetooth of my computer (macbook) inside my virtual machine, as there are some process that the bluepy library cannot handle sharing the bluetooth.
If that's the problem, please use an usb dongle, if not I'll keep looking!

**Comment by DirtyDeep** [comment]
i shared the bluetooth of host machine,my  virtul machine'OS is linux, But i don't have Usb dongle,i cant help you  verify the problem

**Comment by lucferbux** [comment]
Ok, if your error is:
`Failed to execute management command 'le on' (code: 12, error: Not Supported)`
It means bluepy cannot activate ble in your bluetooth card, that means either you don't have a ble card or your virtual machine doesn't talk properly to your host machine to turn on the low enery mode in your bluetooth.

I recommend using a ble dongle (im currently using the one from tp-link) in order to work properly.
This problem is derived from bluepy so you might wanna report the issue there too, as they have a more deep understanding of the issue.

I will however research a bit more trying to replicate your issue, but as I said, I thing your problem is based on the fact that the library cannot activate the low energy.

**Comment by DirtyDeep** [comment]
ok,thanks for your help！

**Comment by sergiokelevra** [comment]
I can't run hcitool because I'm Runnning on Mac OS High Sierra and as you know OSX does not support the bluez module. I'm going to try it on my macbook running kali linux and I'll come back to you.

I'm sure this is like an easy fix but been frustrating me a lot lately...

**Comment by sergiokelevra** [comment]
so same still getting the same error....

output of hcitool dev


root@Kali:~# hcitool dev
Devices:
	hci0	90:27:E4:F1:79:AB
root@Kali:~# 


and here's still the output of homePwN
Can't figure it out why the crazyradio not showing on hcitool...maybe it's just some bluetooth voodoo....IDK

homePwn >>load discovery/ble                                                                        
Loading module...
[+] Module loaded!
homePwn (discovery/ble) >> set rssi -65                                                             
rssi >> -65
homePwn (discovery/ble) >> show                                                                     
Module Info
===========
 Name
 ----
 |_Discovery BLE devices 

 Description
 -----------
 |_With this module you can discover nearby devices with BLE (Bluetooth Low Energy) active. The result will be sorted by RSSI.

 privileges
 ----------
 |_root

 OS
 --
 |_Linux

 Author
 ------
 |_@josueencinar

 Options (Field = Value)
 -----------------------
 |
 |_timeout = 5  (Timeout to wait for search responses. (In seconds))
 |_rssi = -65 (dB signal to filter (min value, example -60))


homePwn (discovery/ble) >> run                                                                      
Searching BLE devices...

Failed to execute management command 'le on' (code: 12, error: Not Supported)
homePwn (discovery/ble) >>

**Comment by DirtyDeep** [comment]
the author tell me to use USB dongle ,you can have a try

**Comment by antoweb** [comment]
> Ok, if your error is:
> `Failed to execute management command 'le on' (code: 12, error: Not Supported)`
> It means bluepy cannot activate ble in your bluetooth card, that means either you don't have a ble card or your virtual machine doesn't talk properly to your host machine to turn on the low enery mode in your bluetooth.
> 
> I recommend using a ble dongle (im currently using the one from tp-link) in order to work properly.
> This problem is derived from bluepy so you might wanna report the issue there too, as they have a more deep understanding of the issue.
> 
> I will however research a bit more trying to replicate your issue, but as I said, I thing your problem is based on the fact that the library cannot activate the low energy.

Hello,
can you tell me which tp-link model you have and if is compatible with debian?

**Comment by lucferbux** [comment]
> > Ok, if your error is:
> > `Failed to execute management command 'le on' (code: 12, error: Not Supported)`
> > It means bluepy cannot activate ble in your bluetooth card, that means either you don't have a ble card or your virtual machine doesn't talk properly to your host machine to turn on the low enery mode in your bluetooth.
> > I recommend using a ble dongle (im currently using the one from tp-link) in order to work properly.
> > This problem is derived from bluepy so you might wanna report the issue there too, as they have a more deep understanding of the issue.
> > I will however research a bit more trying to replicate your issue, but as I said, I thing your problem is based on the fact that the library cannot activate the low energy.
> 
> Hello @lucferbux ,
> can you tell me which tp-link model you have and if is compatible with debian?

Yes of course, this is the one I'm using: https://www.amazon.com/TP-Link-Bluetooth-Receiver-Controllers-UB400/dp/B07V1SZCY6/ref=sr_1_1?keywords=TP-Link+UB400&qid=1582100705&sr=8-1

I haven't tried in vanilla Debian, currently I've tested in Ubuntu and Raspbian, both derived from Debian, so I hope there's no problem.

**Comment by antoweb** [comment]
> > > Ok, if your error is:
> > > `Failed to execute management command 'le on' (code: 12, error: Not Supported)`
> > > It means bluepy cannot activate ble in your bluetooth card, that means either you don't have a ble card or your virtual machine doesn't talk properly to your host machine to turn on the low enery mode in your bluetooth.
> > > I recommend using a ble dongle (im currently using the one from tp-link) in order to work properly.
> > > This problem is derived from bluepy so you might wanna report the issue there too, as they have a more deep understanding of the issue.
> > > I will however research a bit more trying to replicate your issue, but as I said, I thing your problem is based on the fact that the library cannot activate the low energy.
> > 
> > 
> > Hello @lucferbux ,
> > can you tell me which tp-link model you have and if is compatible with debian?
> 
> Yes of course, this is the one I'm using: https://www.amazon.com/TP-Link-Bluetooth-Receiver-Controllers-UB400/dp/B07V1SZCY6/ref=sr_1_1?keywords=TP-Link+UB400&qid=1582100705&sr=8-1
> 
> I haven't tried in vanilla Debian, currently I've tested in Ubuntu and Raspbian, both derived from Debian, so I hope there's no problem.

@lucferbux Thank you very much

**Comment by antoweb** [comment]
> > > Ok, if your error is:
> > > `Failed to execute management command 'le on' (code: 12, error: Not Supported)`
> > > It means bluepy cannot activate ble in your bluetooth card, that means either you don't have a ble card or your virtual machine doesn't talk properly to your host machine to turn on the low enery mode in your bluetooth.
> > > I recommend using a ble dongle (im currently using the one from tp-link) in order to work properly.
> > > This problem is derived from bluepy so you might wanna report the issue there too, as they have a more deep understanding of the issue.
> > > I will however research a bit more trying to replicate your issue, but as I said, I thing your problem is based on the fact that the library cannot activate the low energy.
> > 
> > 
> > Hello @lucferbux ,
> > can you tell me which tp-link model you have and if is compatible with debian?
> 
> Yes of course, this is the one I'm using: https://www.amazon.com/TP-Link-Bluetooth-Receiver-Controllers-UB400/dp/B07V1SZCY6/ref=sr_1_1?keywords=TP-Link+UB400&qid=1582100705&sr=8-1
> 
> I haven't tried in vanilla Debian, currently I've tested in Ubuntu and Raspbian, both derived from Debian, so I hope there's no problem.

@lucferbux Thanks just purchased a new blettoth tp-link and all works good!
