### ISSUE TITLE
Make able to run install.sh unatended

### ISSUE THREAD

**Issue by p0l0** [ElevenPaths/HomePWN#8]
Currently it is not possible to run install.sh unatended, because you are being asked if you want to create a virtual environment or not.

This could be skipped if you were able to specify this via commandline argument.

**Comment by p0l0** [comment]
This would be a proposal to solve this issue:

https://github.com/ElevenPaths/HomePWN/pull/9

**Comment by Josue87** [comment]
Done. Thank you.
